// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package stores

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Status      string             `json:"status"`
	TotalAmount pgtype.Numeric     `json:"total_amount"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type OrderItem struct {
	ID        pgtype.UUID    `json:"id"`
	OrderID   pgtype.UUID    `json:"order_id"`
	ProductID pgtype.UUID    `json:"product_id"`
	UnitPrice pgtype.Numeric `json:"unit_price"`
	Quantity  int32          `json:"quantity"`
}

type Product struct {
	ID    pgtype.UUID    `json:"id"`
	Name  string         `json:"name"`
	Price pgtype.Numeric `json:"price"`
}

type Stock struct {
	ProductID pgtype.UUID        `json:"product_id"`
	Quantity  int32              `json:"quantity"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID `json:"id"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	FullName     string      `json:"full_name"`
}
