// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package stores

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	// ============================================================================
	// WRITE QUERIES (Primary Node)
	// ============================================================================
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeductStock(ctx context.Context, arg DeductStockParams) (Stock, error)
	GetOrderDetails(ctx context.Context, id pgtype.UUID) (Order, error)
	GetOrderItems(ctx context.Context, orderID pgtype.UUID) ([]GetOrderItemsRow, error)
	GetProductByID(ctx context.Context, id pgtype.UUID) (Product, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// ============================================================================
	// READ QUERIES (Replica Node)
	// ============================================================================
	GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error)
	GetUserOrders(ctx context.Context, userID pgtype.UUID) ([]GetUserOrdersRow, error)
	ListProducts(ctx context.Context) ([]ListProductsRow, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (UpdateOrderStatusRow, error)
	UpdateStock(ctx context.Context, arg UpdateStockParams) (Stock, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
}

var _ Querier = (*Queries)(nil)
