// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quries_write.sql

package stores

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (user_id, status, total_amount)
VALUES ($1, $2, $3)
RETURNING id, user_id, status, total_amount, created_at
`

type CreateOrderParams struct {
	UserID      pgtype.UUID    `json:"user_id"`
	Status      string         `json:"status"`
	TotalAmount pgtype.Numeric `json:"total_amount"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, arg.UserID, arg.Status, arg.TotalAmount)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalAmount,
		&i.CreatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (order_id, product_id, unit_price, quantity)
VALUES ($1, $2, $3, $4)
RETURNING id, order_id, product_id, unit_price, quantity
`

type CreateOrderItemParams struct {
	OrderID   pgtype.UUID    `json:"order_id"`
	ProductID pgtype.UUID    `json:"product_id"`
	UnitPrice pgtype.Numeric `json:"unit_price"`
	Quantity  int32          `json:"quantity"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.UnitPrice,
		arg.Quantity,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.UnitPrice,
		&i.Quantity,
	)
	return i, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (name, price)
VALUES ($1, $2)
RETURNING id, name, price
`

type CreateProductParams struct {
	Name  string         `json:"name"`
	Price pgtype.Numeric `json:"price"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct, arg.Name, arg.Price)
	var i Product
	err := row.Scan(&i.ID, &i.Name, &i.Price)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (email, password_hash, full_name)
VALUES ($1, $2, $3)
RETURNING id, email, full_name
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	FullName     string `json:"full_name"`
}

type CreateUserRow struct {
	ID       pgtype.UUID `json:"id"`
	Email    string      `json:"email"`
	FullName string      `json:"full_name"`
}

// ============================================================================
// WRITE QUERIES (Primary Node)
// ============================================================================
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.FullName)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.Email, &i.FullName)
	return i, err
}

const deductStock = `-- name: DeductStock :one
UPDATE stock
SET quantity = quantity - $2,
    updated_at = CURRENT_TIMESTAMP
WHERE product_id = $1 AND quantity >= $2
RETURNING product_id, quantity, updated_at
`

type DeductStockParams struct {
	ProductID pgtype.UUID `json:"product_id"`
	Quantity  int32       `json:"quantity"`
}

func (q *Queries) DeductStock(ctx context.Context, arg DeductStockParams) (Stock, error) {
	row := q.db.QueryRow(ctx, deductStock, arg.ProductID, arg.Quantity)
	var i Stock
	err := row.Scan(&i.ProductID, &i.Quantity, &i.UpdatedAt)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET status = $2
WHERE id = $1
RETURNING id, status
`

type UpdateOrderStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

type UpdateOrderStatusRow struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (UpdateOrderStatusRow, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.Status)
	var i UpdateOrderStatusRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const updateStock = `-- name: UpdateStock :one
UPDATE stock
SET quantity = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE product_id = $1
RETURNING product_id, quantity, updated_at
`

type UpdateStockParams struct {
	ProductID pgtype.UUID `json:"product_id"`
	Quantity  int32       `json:"quantity"`
}

func (q *Queries) UpdateStock(ctx context.Context, arg UpdateStockParams) (Stock, error) {
	row := q.db.QueryRow(ctx, updateStock, arg.ProductID, arg.Quantity)
	var i Stock
	err := row.Scan(&i.ProductID, &i.Quantity, &i.UpdatedAt)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET email = COALESCE($2, email),
    full_name = COALESCE($3, full_name)
WHERE id = $1
RETURNING id, email, full_name
`

type UpdateUserParams struct {
	ID       pgtype.UUID `json:"id"`
	Email    string      `json:"email"`
	FullName string      `json:"full_name"`
}

type UpdateUserRow struct {
	ID       pgtype.UUID `json:"id"`
	Email    string      `json:"email"`
	FullName string      `json:"full_name"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.Email, arg.FullName)
	var i UpdateUserRow
	err := row.Scan(&i.ID, &i.Email, &i.FullName)
	return i, err
}
