// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: qurues_read.sql

package stores

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOrderDetails = `-- name: GetOrderDetails :one
SELECT o.id, o.user_id, o.status, o.total_amount, o.created_at
FROM orders o
WHERE o.id = $1
`

func (q *Queries) GetOrderDetails(ctx context.Context, id pgtype.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderDetails, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalAmount,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderItems = `-- name: GetOrderItems :many
SELECT oi.id, oi.product_id, p.name AS product_name, oi.unit_price, oi.quantity, (oi.unit_price * oi.quantity) AS subtotal
FROM order_items oi
JOIN products p ON oi.product_id = p.id
WHERE oi.order_id = $1
`

type GetOrderItemsRow struct {
	ID          pgtype.UUID    `json:"id"`
	ProductID   pgtype.UUID    `json:"product_id"`
	ProductName string         `json:"product_name"`
	UnitPrice   pgtype.Numeric `json:"unit_price"`
	Quantity    int32          `json:"quantity"`
	Subtotal    int32          `json:"subtotal"`
}

func (q *Queries) GetOrderItems(ctx context.Context, orderID pgtype.UUID) ([]GetOrderItemsRow, error) {
	rows, err := q.db.Query(ctx, getOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrderItemsRow
	for rows.Next() {
		var i GetOrderItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.ProductName,
			&i.UnitPrice,
			&i.Quantity,
			&i.Subtotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, price
FROM products
WHERE id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(&i.ID, &i.Name, &i.Price)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, full_name
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one

SELECT id, email, full_name
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID       pgtype.UUID `json:"id"`
	Email    string      `json:"email"`
	FullName string      `json:"full_name"`
}

// ============================================================================
// READ QUERIES (Replica Node)
// ============================================================================
func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(&i.ID, &i.Email, &i.FullName)
	return i, err
}

const getUserOrders = `-- name: GetUserOrders :many
SELECT id, status, total_amount, created_at
FROM orders
WHERE user_id = $1
ORDER BY created_at DESC
`

type GetUserOrdersRow struct {
	ID          pgtype.UUID        `json:"id"`
	Status      string             `json:"status"`
	TotalAmount pgtype.Numeric     `json:"total_amount"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUserOrders(ctx context.Context, userID pgtype.UUID) ([]GetUserOrdersRow, error) {
	rows, err := q.db.Query(ctx, getUserOrders, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserOrdersRow
	for rows.Next() {
		var i GetUserOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.TotalAmount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT p.id, p.name, p.price, COALESCE(s.quantity, 0) AS stock_quantity
FROM products p
LEFT JOIN stock s ON p.id = s.product_id
ORDER BY p.name ASC
`

type ListProductsRow struct {
	ID            pgtype.UUID    `json:"id"`
	Name          string         `json:"name"`
	Price         pgtype.Numeric `json:"price"`
	StockQuantity int32          `json:"stock_quantity"`
}

func (q *Queries) ListProducts(ctx context.Context) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.StockQuantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
